https://github.com/lervag/vimtex
https://github.com/sqshq/sampler
https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt
getfattr -d
sound process - sox
>https://ru.wikipedia.org/wiki/Util-linux
wmctrl -lx
setxkbmap -layout us_intl,ru \ # включаем us_intl -option compose:rctrl # настраиваем клавишу Compose 
xdotool for auto battle touhou and navigate + xbindkeys 
tsort shuf comm fmt factor seq
https://gist.github.com/XVilka/8346728
https://www.kernel.org/doc/html/v4.12/dev-tools/kmemcheck.html
https://lwn.net/Articles/132196/
https://github.com/soimort/translate-shell
rmlint
>https://linux.die.net/man/1/djvu
>+https://github.com/junegunn/fzf
* csv
http://bconnelly.net/working-with-csvs-on-the-command-line/
csvtool
csvkit
https://github.com/andmarti1424/sc-im
* >+https://github.com/jhawthorn/fzy
>https://github.com/b4b4r07/enhancd
make keybind open tmux pane right vertical 20% list files current dir

socat  nc -U  nc -uU
echo "string_to_encrypt" | openssl enc -pass file:secret.key -e -aes-256-cbc -a -salt
U2FsdGVkX194R0GmFKCL/krYCugS655yLhf8aQyKNcUnBs30AE5lHN5MXPjjSFML
echo 'U2FsdGVkX194R0GmFKCL/krYCugS655yLhf8aQyKNcUnBs30AE5lHN5MXPjjSFML' | openssl enc -pass file:secret.key -d -aes-256-cbc -a -salt
string_to_encrypt

read -p "Press any key to continue (autocontinue in 30 seconds) " -t 30 -n 1
>>>>>https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html


0 * * * * export DISPLAY=:0 && notify-send "Hour pass! `date` $(date)" 
>http://skarnet.org/software/s6/
>https://circus.readthedocs.io/en/latest/
* dbus
d-feet
dbus.service
https://dbus.freedesktop.org/doc/dbus-monitor.1.html
* systemd
http://wiki.opennet.ru/Systemd_%D0%B4%D0%BB%D1%8F_%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BE%D0%B2,_%D1%87%D0%B0%D1%81%D1%82%D1%8C_3:_HOW-TO:_%D0%BF%D1%80%D0%B5%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_SysV_init-%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%B0_%D0%B2_systemd_service-%D1%84%D0%B0%D0%B9%D0%BB
http://0pointer.de/public/systemd-man/
http://tux-the-penguin.blogspot.ru/2010/09/systemd.html
http://tux-the-penguin.blogspot.ru/2010/09/systemd-ii.html
http://0pointer.de/public/systemd-man/systemd.special.html
man journalctl
- lsof :: https://habrahabr.ru/company/ruvds/blog/337934/
>http://mbreen.com/m4.html
>https://www.gnu.org/software/autogen/
>https://www.gnu.org/software/m4/manual/m4-1.4.15/html_node/index.html#Top
>http://www.shlomifish.org/open-source/resources/text-processing-tools/
paste
>http://citkit.ru/articles/18/
>http://www.linuxcenter.ru/lib/books/zlp/
* cron
>https://crontab.guru/every-1-hour
http://blog.endpoint.com/2008/12/best-practices-for-cron.html
* boot
загрузочные параметры ядра
cat /proc/cmdline

лог ядра
dmesg

* virt
virsh list
virt-manager
https://libvirt.org/drvqemu.html

* zsh
https://habrahabr.ru/post/82537/
https://habrahabr.ru/post/157283/
>! use: https://github.com/robbyrussell/oh-my-zsh
* all new
https://habrahabr.ru/company/itsumma/blog/336754/
https://habrahabr.ru/post/336780/
https://habrahabr.ru/post/336656/
https://habrahabr.ru/post/174449/
>https://www.shellhacks.com/ru/fake-file-access-modify-change-timestamps-linux/
>https://www.stableit.ru/search/label/Linux%20kernel
>https://i3wm.org/docs/userguide.html#keybindings
>https://serveradmin.ru
>https://superuser.com/questions/925286/does-tcpdump-bypass-iptables
- git :: https://www.gitbook.com/book/0xax/linux-insides/details
- selinux :: https://habrahabr.ru/company/kingservers/blog/209644/
- ffmpeg :: https://habrahabr.ru/post/333664/
- shell unix :: https://www.amazon.com/dp/0201433079
- unix shell :: http://www.faqs.org/faqs/unix-faq/programmer/faq/
uzbl browser
https://wiki.archlinux.org/index.php/Vimprobable
# record ffmpeg video, convert to gif, upload to imgur, post to gits, share link
https://github.com/icholy/ttygif
https://github.com/pipeseroni/pipes.sh
https://github.com/zquestz/s
https://github.com/schandinat/green
https://github.com/aria2/aria2
https://leanpub.com/the-tao-of-tmux/read
https://robots.thoughtbot.com/a-tmux-crash-course
http://www.hamvocke.com/blog/a-quick-and-easy-guide-to-tmux/
pdftohtml to tmp and w3m it

https://github.com/sjbach/viewglob
http://aplawrence.com/Words2005/2005_05_25.html
https://bbs.archlinux.org/viewtopic.php?id=103847
http://www.i0i0.de/toolchest/emv
vidir
w3m
- tig :: for view git repo

- CD :: Write script that peroidically search bash history for cd,
 extract paths, make absolutes, and sort it by most usable, and make 
 some extra aliases for cmd like `go` a, go b, go c etc. or j
      in file manager store most visitable paths
 autojump

>>>http://hokstad.com/5-simple-ways-to-troubleshoot-using-strace
>http://www.brendangregg.com/linuxperf.html
 >- tty :: https://habrahabr.ru/company/neobit/blog/330764/
>http://inf.ocs.ku.ac.th/Download/Wiley.Linux.Command.Line.and.Shell.Scripting.Bible.May.2008.pdf
>http://www.opennet.ru/opennews/art.shtml?num=46598
>https://www.tecmint.com/manage-services-using-systemd-and-systemctl-in-linux/
>https://likegeeks.com/expect-command/
* w3m
>https://box.matto.nl/w3m.html
* colors
>http://www.futurile.net/2016/06/15/xterm-256color-themes-molokai-terminal-theme/
* NEWBIE GUIDE
>https://likegeeks.com/main-linux-commands-easy-guide/

* arch
>https://wiki.archlinux.org/index.php/Systemd/Timers_(Русский)
* learn
>http://www.quizful.net/test
>http://cat-v.org/
>http://www.linfo.org/index.html
>http://www.brendangregg.com/linuxperf.html
>http://www.linuxlib.ru/
>http://rus-linux.net/MyLDP/BOOKS/Architecture-Open-Source-Applications/index.html
>https://wiki.linuxfoundation.org/start
* User
>>debian.pro
>http://www.tuxradar.com/content/command-line-tricks-smart-geeks
>https://www.google.ru/search?q=linux+console+speed+work+tips&gws_rd=cr,ssl&ei=C8M2WZypOsGB6ASrjaiwBw
>http://www.remoteshaman.com/unix/common/jemalloc-for-all-app-in-linux
>http://linux.yaroslavl.ru/docs/conf/fs/fhs-full.html
>https://wiki.ubuntu.com/SystemdForUpstartUsers
>http://help.ubuntu.ru/wiki/%D0%BC%D0%BE%D0%BD%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%BE%D0%B2_%D0%B4%D0%B8%D1%81%D0%BA%D0%BE%D0%B2
>https://sites.google.com/site/easylinuxtipsproject/Home
>https://linux-notes.org/ispol-zovanie-ionice-v-unix-linux/
** soft
      >https://github.com/jarun/Buku
      >http://zenway.ru/category/internetpo
** LVM
>https://ru.wikipedia.org/wiki/DRBD
** time
>http://help.ubuntu.ru/wiki/%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%BD%D0%BE%D0%B5_%D0%B2%D1%80%D0%B5%D0%BC%D1%8F_windows_%D0%B8_ubuntu
* books
>http://rus-linux.net/nlib.php?name=/MyLDP/freesoft/FreeBooks/free20books.html
* Bash bash
>https://github.com/koalaman/shellcheck
ctrl-j - CR like ctrl-m
>>http://tldp.org/LDP/abs/html/index.html
 write intro by
>!>https://www.opennet.ru/docs/RUS/bash_scripting_guide/c301.html
    >https://likegeeks.com/main-linux-commands-easy-guide/
    >https://likegeeks.com/basic-linux-commands-part2/
>>https://likegeeks.com/expect-command/
>>>http://wiki.bash-hackers.org/doku.php
>>>https://habrahabr.ru/company/ruvds/blog/326826/
>http://wiki.bash-hackers.org/scripting/newbie_traps
>https://habrahabr.ru/post/221273/
>https://stedolan.github.io/jq/
>http://www.commandlinefu.com/commands/browse
>https://www.opennet.ru/docs/RUS/bash_scripting_guide/x288.html
>curl wttr.in
>http://rus-linux.net/MyLDP/BOOKS/Linux_Foundations/13/ch13.html
>https://www.opennet.ru/docs/RUS/bash_scripting_guide/c5358.html
>http://rus-linux.net/MyLDP/BOOKS/abs-guide/flat/abs-book.html
>https://habrahabr.ru/company/ruvds/blog/325522/
>https://habrahabr.ru/post/151771/
* DB
>http://www.linas.org/linux/db-non-sql.html
* kernel
>https://lwn.net/Articles/132196/
>https://habrahabr.ru/post/336470/
>https://dri.freedesktop.org/docs/drm/process/stable-api-nonsense.html#stable-kernel-source-interfaces
>https://github.com/torvalds/linux/blob/master/Documentation/x86/boot.txt
>https://lists.kernelnewbies.org/pipermail/kernelnewbies/2016-August/date.html#16694
>https://proninyaroslav.gitbooks.io/linux-insides-ru/content/Booting/linux-bootstrap-1.html
>https://proninyaroslav.gitbooks.io/linux-insides-ru/content/index.html
>https://github.com/proninyaroslav/linux-insides-ru
>https://www.opennet.ru/base/dev/dev_linux_modules.txt.html
>http://kernel-handbook.alioth.debian.org/
>https://lwn.net/Kernel/
>http://www.linfo.org/kernel_space.html
>http://rus-linux.net/MyLDP/BOOKS/knm.pdf
** build
>http://help.ubuntu.ru/wiki/%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D0%B0_%D1%8F%D0%B4%D1%80%D0%B0
>http://wiki.opennet.ru/%D0%A1%D0%B1%D0%BE%D1%80%D0%BA%D0%B0_%D1%8F%D0%B4%D1%80%D0%B0_/_make_kernel
>http://eax.me/linux-kernel-build/
* NET network
>http://rus-linux.net/MyLDP/BOOKS/nag-20/x1312.htm
>http://help.ubuntu.ru/wiki/%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0_%D1%81%D0%B5%D1%82%D0%B8_%D0%B2_linux
>https://www.ibm.com/developerworks/ru/library/l-linux-networking-stack/
>https://habrahabr.ru/post/326574/
>https://www.youtube.com/watch?v=BJSITWkSDQg
>https://shells.red-pill.eu/
>https://ru.wikibooks.org/wiki/Iptables
>http://rus-linux.net/MyLDP/BOOKS/nag-20/x1312.htm
** iptables
>https://wiki.archlinux.org/index.php/Simple_stateful_firewall_(%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9)
>https://wiki.archlinux.org/index.php/Iptables_(%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9)
** wireshark/tcpdump
>https://www.youtube.com/watch?list=PLtPJ9lKvJ4oiKPQ9GXOvntj44Eu8IGAJK&v=Cc5wi1bxmpc
** net sim
>http://www.brianlinkletter.com/open-source-network-simulators/
>https://wiki.linuxfoundation.org/networking/netem
>http://imunes.net/
>https://habrahabr.ru/company/pentestit/blog/244955/
>http://www.net-simulator.org/ru/index.shtml
>http://ivirt-it.ru/mininet/
* ssh
>http://rus-linux.net/MyLDP/sec/SSH-Tunneling.html

* Terminals
>http://tldp.org/HOWTO/Text-Terminal-HOWTO.html

* sysdev											:dev:
      https://habrahabr.ru/post/124789/
      www.netzmafia.de/skripten/unix/linux-daemon-howto.html
      https://ru.wikipedia.org/wiki/POSIX_Threads
      DTrace
      http://www.opennet.ru/docs/FAQ/programming/unix-programming.html
      BFQ
      https://habrahabr.ru/post/326138/
      http://ccfit.nsu.ru/~deviv/courses/unix/unix/ng1e3.html

** IPC
      Сигналы
      Семафоры
      Сообщения
      Сокеты?
      разделяемая Память
      Пайп - канал
      Файл

* *Securiti*
      https://www.cyberciti.biz/faq/howto-check-linux-rootkist-with-detectors-software/
      https://www.howtogeek.com/howto/30184/10-ways-to-generate-a-random-password-from-the-command-line/
** hack 
      https://codeby.net/bezopasnost/stress-test-seti-dos-s-ispolzovaniem-hping3-i-spufingom-ip-v-kali-linux/
      https://codeby.net/bezopasnost/kak-vzlomat-svoju-set-i-povysit-ejo-bezopasnost-s-pomoshhju-kali-linux/
      https://www.kali.org/tutorials/kali-linux-android-linux-deploy/

* Test											:Imp:
>https://ualinux.com/ru/online-test
* Virtualization
      зачем мне нужны контейнеры. (кроме деплоя всякого)
      - для сборки с dev- пакетами
      - для экспериментов, чтобы не захламлять
      - держать разные среды и не портить базовую систему, не переставлять
      - ? другой дистриб
      - Запуск нехороших, странных приложений(скайп, вайбер..)
      - анон, хранение отдельно куков, окружений
      - одна среда на разных компах? если жить в контейнере
** qemu
>http://xgu.ru/wiki/Linux_Bridge
>http://www.h7.dion.ne.jp/~qemu-win/HowToNetwork-en.html
>https://wiki.archlinux.org/index.php/QEMU
>https://trello.com/c/ydDw9zS6/247-qemunet#
>http://www.ossportal.ru/technologies/kvm/blogs/140
** Vbox
*Удобна для написаня ОС, ядра. тестов ядер и ос.*
>https://www.virtualbox.org/manual/ch08.html
>https://www.perkin.org.uk/posts/create-virtualbox-vm-from-the-command-line.html
>http://www.virtualbox.org/manual/ch09.html#otherextpacks
>xmodulo.com/how-to-manage-virtualbox-vms-on-remote-headless-server.html
>http://eax.me/vboxmanage/
** libvirt
>http://www.libvirt.org/apps.html
** lxc
>http://bazhenov.me/blog/2015/02/11/lxc-for-developer.html
>https://linuxcontainers.org/lxcfs/introduction/
>http://vasilisc.com/lxc-1-0-blog-post-series
>http://www.netpatch.ru/research/cgroups/2014/03.11-cgroups-basic-practice.html
>https://habrahabr.ru/company/selectel/blog/279281/
>http://help.ubuntu.ru/wiki/%D1%80%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE_%D0%BF%D0%BE_ubuntu_server/%D0%B2%D0%B8%D1%80%D1%82%D1%83%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F/lxc
** docker
>http://eax.me/docker/
>https://habrahabr.ru/post/253877/
** openvz
* other
>http://gource.io/
asciinema
curl wttr.in

* man Read.
  tmpfiles.d
* Learn Use!									     :use:							
      abrtd wtmp
      zic
      ttysnoop :: spy console
      sloccount
      imagemagick aview convert
      ptrace
      davfs2
      shar
      upower
      powertop
      truncate -s 0 file
      resize2fs
      losetup
      asciitopgm pbmtoascii pgm
      pidstat
      samba, smbtree, nmblookup
      smbtree -S
      nmblookup NAME
      sudo mount -t cifs //10.4.20.51/share /mnt -o username=ksi

      fc -ln #history make script
      ack
      uzbl
      yacpi
      whiptail
      lshw
      nmap
      flock
!!!!  locate (for find example pg_hba.conf)
      debootstrap
      trap
      smstools3
      tasksel
       типы файлов в линуксе (обычный, директория, pipe, socket, block, char )
      rabbitmq 
       cmd  cmp сравнение файлов
       mknod или mkfifo
    streamer
      msgcat --color=test
      pidof
      pgrep
      flock
      ionice
      tcpdump
      - gcp :: copier like cp in PY
      https://taskwarrior.org/docs/examples.html
      tput
      http://www.f-notes.info/linux:linux_command
      expect
      fuser
      ?? | column -t
      while true; do some && break; done
      multitail
      tail -f
      nohup
      sudo !!
      script
      xargs -i ?? {}
      expand unexpand
      openssl -connect
      gtypist
      iperf
      CheckInstall
      dpkg -L libfoo
      dpkg -S /usr/include/foo.h
      +stat
      +file
      sed
      lsattr
      chattr
      tc
      users
      +nproc
      lscpu
      lsblk
      blkid
      +scp
      +ssh
      nc

** dev
      readelf
      ipcs
      nm
      ltrace strace 
      dtrace systemtap
      perf
      as
** statistic
      vmstat
      free -h
      df -h
      tcpdump -i enp4s0
      iotop
      iostat #from sysstat
      sudo iftop
      nmon
      atop
      iptraf
      dstat
** notify
      wall
      inotify
      inotifywait -m PATH
      >https://www.ibm.com/developerworks/ru/library/l-ubuntu-inotify/
      write user tty
** logs
      journal -xe
      dmesg -w

* Concurency
>https://habrahabr.ru/company/nordavind/blog/176541/
* *OSDEV*
- video :: https://stepik.org/course/%D0%9E%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B-1780/syllabus?module=2
>http://pages.cs.wisc.edu/~remzi/OSTEP/
>http://wiki.osdev.org/Category:Bare_bones_tutorials
>http://css.csail.mit.edu/6.858/2014/readings/i386.pdf
>https://en.wikipedia.org/wiki/Hobbyist_operating_system_development
>http://os.phil-opp.com/entering-longmode.html#paging
>http://cpubook.ru/%D0%A0%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D1%8B%20%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%BE%D1%80%D0%B0/%D0%A0%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%20EAX/
>http://ru.osdev.wikia.com/wiki/%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F
>http://ru.osdev.wikia.com/wiki/%D0%92%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BB%D0%B8%D0%BD%D0%B8%D0%B8_A20
>http://www.frolov-lib.ru/books/bsp.old/v02/ch8.htm
>https://littleosbook.github.io/
>https://habrahabr.ru/company/nordavind/blog/176541/
>http://greenteapress.com/thinkos/
>https://ru.hexlet.io/courses/operating_systems
>http://wiki.osdev.org/Required_Knowledge
>https://github.com/SamyPesse/How-to-Make-a-Computer-Operating-System
*** Assembler
>http://cs.lmu.edu/~ray/notes/gasexamples/
>https://ru.wikibooks.org/wiki/%D0%90%D1%81%D1%81%D0%B5%D0%BC%D0%B1%D0%BB%D0%B5%D1%80_%D0%B2_Linux_%D0%B4%D0%BB%D1%8F_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%81%D1%82%D0%BE%D0%B2_C
>http://dbp-consulting.com/tutorials/debugging/basicAsmDebuggingGDB.html
>https://www.recurse.com/blog/7-understanding-c-by-learning-assembly
- video :: https://www.youtube.com/channel/UCG5p_AY0z7WDAgH6j-oCa9g/videos
>http://demo.yasp.me/
>https://blogs.oracle.com/ksplice/hello-from-a-libc-free-world-part-1

* appearence
** conky
>http://conky.pitstop.free.fr/wiki/index.php5?title=Goto/offset/voffset_(en)
* perfomance
>http://www.brendangregg.com/blog/2016-01-20/ebpf-offcpu-flame-graph.html
* MAIL mail
>http://mailutils.org/
mutt
slrn
alpine
NNTP

