* Нейросеть рисующая по пайплайную, каждый этап отдельаня сеть, отдельно натрененая: скетч, лайнт, флет, цвет, тени(ао, собст..)...
Artistic render - рендерить каждый элемент но стилизую - отражения упращая до мазков и тп
    А если научить НС рендерить так, одтельно, то можно менять  сцену и ракурс и получится движок
    добавить сети умеющие воспроизводить объекты реальности, их элементы. Так что модель = нс
    Алгоритмы проги которые будут рисовать, генерить изображения.. Даже просто алгоритмы, куб рисуют, с разных ракурсов, по разному раскрасить, но учитывая правила! Компоновать объекты, балансировать, делать динамику. генерить асбтрактные композиции. Усложнять дизайн. svg, симметрии, повторы, фракталы. цветовые сочетания, учёт светотени. анатомия?
    Или хотябы автоматизация рутинных процессов в рисовании: обводка, усложнение диза, варианты композиции, рандом, градиенты... палитры
Нейросеть для палитр, лайна, покраса, светотени... скетча? построения?


https://vc.ru/selectel/41002-instrukciya-sozdanie-neyronnoy-seti-bez-navykov-programmirovaniya

https://github.com/googlecodelabs/tensorflow-for-poets-2

https://pytorch.org/
https://github.com/pytorch/pytorch
https://github.com/tensorflow/tensorflow
http://playground.tensorflow.org/#activation=tanh&batchSize=10&dataset=circle&regDataset=reg-plane&learningRate=0.03&regularizationRate=0&noise=0&networkShape=4,2&seed=0.27784&showTestData=false&discretize=false&percTrainData=50&x=true&y=true&xTimesY=false&xSquared=false&ySquared=false&cosX=false&sinX=false&cosY=false&sinY=false&collectStats=false&problem=classification&initZero=false&hideText=false
https://ru.wikipedia.org/wiki/%D0%93%D0%BB%D1%83%D0%B1%D0%BE%D0%BA%D0%BE%D0%B5_%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5
OpenNN
 TensorFlow.
дерева поиска Монте-Карло
http://neuralnetworksanddeeplearning.com/
https://github.com/mnielsen/neural-networks-and-deep-learning

Trevor Hastie et al. "The Elements of Statistical Learning"
Vladimir N. Vapnik "The Nature of Statistical Learning Theory"
Christopher M. Bishop "Pattern Recognition and Machine Learning"
http://www.deeplearning.net/tutorial/ | https://www.hackerrank.com/domains/ai | https://github.com/pytorch/examples
https://www.kaggle.com/ | http://mltrainings.ru/
https://www.indeed.com/q-deep-learning-jobs.html
www.deeplearningbook.org
https://blog.openai.com/adversarial-example-research/
http://pages.cs.wisc.edu/~bolo/shipyard/neural/local.html
http://www.machinelearning.ru/wiki/index.php?title=%D0%9C%D0%B0%D1%88%D0%B8%D0%BD%D0%BD%D0%BE%D0%B5_%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5
НС с удалящимися и появляющимися нейронами по некому критерию(ген) во "сне"
