#!/bin/bash
export BASHCONF="D:\dotfiles\windows\bashconfig"
export BASEDIR='D:\dotfiles\windows'
export DOC=https://anokata@bitbucket.org/anokata/doc.git
export DOCDIR='D:\doc'
export PATH=$PATH:'D:\dotfiles\windows\bin'
export CLICOLOR="YES"
export TERM=xterm-256color
export PROMPT_COMMAND="history -a; history -c;history -r"
# echo from win bash conf $BASHCONF
alias bashrc='vim $BASHCONF; source $BASHCONF'
alias bashsrc='source $BASHCONF'

HISTCONTROL=ignoreboth
HISTSIZE=10000
HISTFILESIZE=20000
set -o vi
stty -ixon # for not stop draw at C-s (C-q restore)
bind -x '"\C-o"':"fg"

source $BASEDIR/lib/alias.sh
source $BASEDIR/lib/color.sh
source $BASEDIR/lib/tmux.sh

function git_dirty {
    local status=$(git status --porcelain 2>/dev/null) 
    if [[ $status != "" ]]; then echo -e "*"; fi
}

# export PS1="$GREY\u$GRAY@$GREY\w$R\$(git_dirty)$GRAY\$ $RESET"
export PS1="$Y\u$GR@$G\w$R\$(git_dirty)$W\$ $RESET"

shopt -s extglob
shopt -s cmdhist 
shopt -s dotglob     
shopt -s histappend
shopt -s cdspell

# if [ -e ~/.home.sig -o -e ~/.work.sig ]; then 
#     _try_tmux_run
# fi
#_try_tmux_run
