#!/bin/bash
source bashconf.sh
say "Config files coping..."
cp ~/dotfiles/.bashrc ~/
cp ~/dotfiles/.vim ~/
mkdir -p ~/.vim/autoload/
mkdir -p ~/.vim/colors/
cp ~/dotfiles/my.vim ~/.vim/colors
cp ~/dotfiles/Linux/configs/.vim/autoload/plug.vim ~/.vim/autoload
cp ~/dotfiles/.tmux.conf ~/
#.config/i3/config
#bin -r
#vifmrc
#.Xresources
#.xprofile
#.xinputrc
#.xbindkeysrc
#
say "done"
