#!/bin/bash
OPAC=0.9
if which transset 2>/dev/null; then
    transset -p $OPAC
elif [ -f /usr/bin/transset-df 2>/dev/null ]; then
    transset-df -p $OPAC
fi
if which feh 2>/dev/null; then
    feh --bg-fill -s ~/wall.jpg 
fi
if which xcompmgr 2>/dev/null; then if ! pidof xcompmgr; then xcompmgr& fi fi #if not running
if which i3-msg 2>/dev/null; then
    i3-msg "bar mode invisible" 
fi

