#!/bin/bash
OPAC=1
if which transset; then
    transset -p $OPAC
elif [ -f /usr/bin/transset-df ]; then
    transset-df -p $OPAC
fi
if which feh; then
    feh --bg-fill -s ~/wall.jpg 
fi
if which xcompmgr; then if ! pidof xcompmgr; then xcompmgr& fi fi #if not running
i3-msg "bar mode invisible" 
