https://play.google.com/store/apps/details?id=com.vladi.weatherexplorer
https://www.youtube.com/watch?v=xy9LLUUZ6ic

>https://xakep.ru/2017/06/27/old-android-server/
>https://forum.xda-developers.com/android/general/kali-linux-android-phone-metasploit-t3057423
>>OTG on root https://play.google.com/store/apps/details?id=eu.chainfire.stickmount
>>>>>>https://wikileaks.org/ciav7p1/cms/files/AIvI-M-RL1.pdf
>>http://cecs.wright.edu/~pmateti/Courses/4900/Lectures/Internals/Android-Internals-2.html
>>>https://www.google.ru/search?q=android+internals+system+init+process&gws_rd=cr,ssl&ei=E1dnWc3HDujp6ASn4rSwDg
https://anatomyofandroid.com/2013/10/15/zygote/
https://androidforums.com/threads/list-of-fastboot-command.714676/
http://benno.id.au/blog/2007/11/13/android-under-the-hood
try pull /etc/init.rc and add sh copy at boot
* chroot
https://technohackerblog.blogspot.co.id/2016/07/running-arch-linux-in-chroot-on-android.html
https://blackarch.org/tools.html

cd mnt
mount -t proc proc proc/
mount --rbind /sys sys/
mount --rbind /dev dev/
mount --rbind /run run/

busybox mount -t proc none ./proc
busybox mount -o rbind /dev ./dev
busybox mount -t sysfs none ./sys
busybox mount -t tmpfs none ./tmp
busybox mount -o size=10%,mode=0755 -t tmpfs none ./run
cp /etc/resolv.conf etc/resolv.conf
chroot mnt

* mount
https://github.com/meefik/busybox/releases
ru.meefik.busybox
https://github.com/meefik/linuxdeploy/issues/358
https://javigon.com/2012/09/04/mount-unmount-android-system-images/
http://kevinboone.net/android_nonroot.html
https://habrahabr.ru/post/221543/
https://superuser.com/questions/117136/how-can-i-mount-a-partition-from-dd-created-image-of-a-block-device-e-g-hdd-u

mknod /dev/loop0 b 7 0
losetup --partscan --find --show disk.img

* sp flash tool
sudo pacman -S libusb modemmanager
sudo gpasswd -a ksi uucp
newgrp - uucp
 sudo vim /etc/udev/rules.d/80-persistent-usb.rules 
SUBSYSTEM=="usb", ACTION=="add", ATTR{idVendor}=="0e8d", ATTR{idProduct}=="*"

sudo vim /etc/udev/rules.d/20-mm-blacklist-mtk.rules
ATTRS{idVendor}=="0e8d", ENV{ID_MM_DEVICE_IGNORE}="1"
ATTRS{idVendor}=="6000", ENV{ID_MM_DEVICE_IGNORE}="1"

sudo service udev restart

* fastboot
fastboot oem list_partition all
fastboot getvar all

* write flash
https://4pda.ru/forum/index.php?showtopic=468628&st=2440
https://4pda.ru/forum/index.php?showtopic=469340&st=2460

- adb root :: https://forum.xda-developers.com/showthread.php?t=2335799

* sh
- PATHS :: /preload/app
- PATHS :: /data/app-lib
- PATHS :: /data/dalvik-cache
- PATHS :: /data/data
*Delete*
from /data/app-lib by comName
from /data/data by comName
from /system/app by apkName
from /data/app by apkName

#!/bin/sh
NAME=$1
SYSPATH=$(pm list packages -f | grep $NAME | cut -d: -f 2 | cut -d = -f 1)
APKNAME=$(pm list packages -f | grep $NAME | cut -d: -f 2 | cut -d = -f 1 | )
COMNAME=$(pm list packages -f | grep $NAME | cut -d: -f 2 | cut -d = -f 2)

rm -r /data/app-lib/$COMNAME/
rm -r /data/data/$COMNAME/
rm $SYSPATH
-----

data/data, data/dalvik cashe, system/lib,system/frammework
script for remove. where get info?
pm list packages 
pm path <app>

https://developer.android.com/develop/index.html
https://developer.android.com/ndk/guides/concepts.html
https://developer.android.com/ndk/guides/cpp-support.html
https://developer.android.com/ndk/guides/stable_apis.html
https://android.stackexchange.com/questions/44049/how-do-i-open-a-text-file-from-a-terminal-window-from-within-the-android-gui

adb shell getevent -l
https://source.android.com/devices/input/touch-devices
https://source.android.com/devices/input/getevent

https://bbs.archlinux.org/viewtopic.php?id=108553
https://stackoverflow.com/questions/9460251/how-do-i-build-a-native-command-line-executable-to-run-on-android
http://gdr.geekhood.net/gdrwpl/vim-android.php

написать простейших баш скриптов для нужного функционала и сделать запускатор по тачу 
например просмотрщик картинок в папке - тач в лево части - промотка вперёд,
без лишнего. только как открывать показывать?


>https://4pda.ru/forum/index.php?showtopic=716237
>http://www.linux-magazine.com/Online/Features/Convert-an-Android-Device-to-Linux
>https://play.google.com/store/apps/details?id=ru.meefik.linuxdeploy
>http://www.elinux.org/Android_Build_System
>https://play.google.com/store/apps/details?id=sk.vx.connectbot
>https://play.google.com/store/apps/details?id=com.coboltforge.dontmind.multivnc
https://play.google.com/store/apps/details?id=com.cuntubuntu
https://www.androidpit.com/turn-your-android-device-into-a-linux-pc-without-rooting

* shell
https://a3nm.net/blog/android_cli.html
https://4pda.ru/forum/index.php?showtopic=508427&st=0#entry25813554
https://developer.android.com/guide/components/services.html?hl=ru
https://4pda.ru/forum/index.php?showtopic=271486&st=3960#entry47728304
https://losst.ru/komandy-v-android-terminal-emulator
https://stanfy.com/blog/android-shell-part-2-starting-%D1%81omponents-you-need-activity-manager-client/
bmgr

* linux
https://en.wikipedia.org/wiki/Android_%28operating_system%29#Development
http://elinux.org/Android_Architecture
https://developer.android.com/guide/platform/index.html
https://source.android.com/

http://www.gsmarena.com/philips_w6500-5802.php

* build
http://www.netmite.com/android/mydroid/development/pdk/docs/build_new_device.html
http://www.lineageosrom.com/2017/01/how-to-build-lineageos-rom-for-any.html

1. Make Backup
>https://4pda.ru/forum/index.php?showtopic=349626
dd if=/dev/block/mmcblk0p13 of=/sdcard/recovery_backup.img
cat /proc/mounts
/dev/block/mmcblk0p15 /system
/dev/block/mmcblk0p16 /cache
/dev/block/mmcblk0p27 /efs
/dev/block/mmcblk0p17 /data
/dev/block/mmcblk0p8 boot
/dev/block/mmcblk0p13 recovery
my:
1. preload :: /emmc@preload /dev/block/mmcblk0p4
2. system  :: /emmc@android /dev/block/mmcblk0p5
3. cache   :: /emmc@cache   /dev/block/mmcblk0p6
4. data    :: /emmc@usrdata /dev/block/mmcblk0p7
5. ebr     :: /emmc@ebr1    /dev/block/mmcblk0p1
6. protect :: /emmc@protect_f /dev/block/mmcblk0p2
7. protect :: /emmc@protect_s /dev/block/mmcblk0p3
8. boot 0  :: /dev/block/mmcblk0boot0
9. boot 1  :: /dev/block/mmcblk0boot1
dd if=/dev/block/mmcblk0boot0 of=/storage/sdcard1/backup/boot0
dd if=/dev/block/mmcblk0boot1 of=/storage/sdcard1/backup/boot1
dd if=/dev/block/mmcblk0p4 of=/storage/sdcard1/backup/preload 
dd if=/dev/block/mmcblk0p5 of=/storage/sdcard1/backup/system  
dd if=/dev/block/mmcblk0p7 of=/storage/sdcard1/backup/data    
dd if=/dev/block/mmcblk0p2 of=/storage/sdcard1/backup/protect 
dd if=/dev/block/mmcblk0p3 of=/storage/sdcard1/backup/protect 
dd if=/dev/block/mmcblk0p1 of=/storage/sdcard1/backup/ebr
dd if=/dev/block/mmcblk0p6 of=/storage/sdcard1/backup/cache

2. Unlock bootloader

- install adb, fastboot
- bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf lib32ncurses5-dev lib32readline6-dev lib32z1-dev libesd0-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev
imagemagick
- openjdk-7-jdk

#!/bin/bash
LINEOS_DIR=~/lineos
mkdir $LINEOS_DIR
mkdir $LINEOS_DIR/bin
mkdir -p $LINEOS_DIR/android/system
curl https://storage.googleapis.com/git-repo-downloads/repo > $LINEOS_DIR/bin/repo
chmod a+x $LINEOS_DIR/bin/repo
PATH="$LINEOS_DIR/bin:$PATH"
cd $LINEOS_DIR/android/system
repo init -u https://github.com/LineageOS/android.git -b cm-13.0
repo sync -c -j2


# spam call
https://play.google.com/store/apps/details?id=org.mistergroup.shouldianswer&referrer=utm_source%3Dhomepage%26utm_medium%3Dbanner%26utm_campaign%3Dmainpagepeople
https://play.google.com/store/apps/details?id=com.numbuster.android
https://play.google.com/store/apps/details?id=com.flexaspect.android.everycallcontrol&referrer=utm_source%3DEveryCaller
