* 1
В отличие от графического интерфейса, в текстовом необходимо четко понимать что и как делается. 
Это развиваем навык рационального мышления. Прежде чем сделать что-то следует подумать и решить как это будет делаться, вместо того
чтобы суетливо искать решение метаясь по всем возможностям. Такой подход учит концентрировать внимание, 
что очень важно, для развития личности

cd
cd ~
cd -
cd ..


change directories to look inside another one? (cd mydir, for 'change directory')

get a quick reminder of the text files in this directory? (ls *.txt, for 'list')

move/rename a file? copy a file? delete a file? (mv myfile newname, cp myfile mycopy, and rm myfile, for 'move', 'copy', and 'remove')

open this file for editing/viewing? (gedit myfile, or leafpad, or nano, or vim, or whatever.)

У всех программ одинаково устроенный интерфейс

* 0 Что даст изучение и умение работы в консоле
Скорость выполнения задач: ...?
простота
позволяте сделать именно то что ты хочешь, экономить время 
полный котроль над ОС, всё можно сделать кратчайшим способом
Автоматизация рутинных задач.
Проще объяснить какие команды выполнить для решения задачи чем объяснять графические манипуляции.
Есть множество задач для которых ещё нет графического интрефейса, а значит твои возможности намного шире.
Много быстрее ввести часть команды и сделать дополнение чем тыкаться через меню.
Можно видеть и понимать что происходит не так.

* -1 shortcuts
>http://www.hongkiat.com/blog/100-keyboard-shortcuts-windows/
*moving*
ctrl-(left, right)
home
end
ctrl-home
ctrl-end
page down
page up
*select*
ctrl-shift-(left, right)

ctrl-n create new
ctrl-o open
ctrl-a select all
ctrl-f find
ctrl-q exit
ctrl-s save
ctrl-x cut
ctrl-c copy
ctrl-v paste
ctrl-z ctrl-y
CTRL-P print


*browser*
ctrl-t new tab
ctrl-w close tab
ctrl-tab
ctrl-shift-tab
ctrl-r F5


>https://unix.stackexchange.com/questions/4126/what-is-the-exact-difference-between-a-terminal-a-shell-a-tty-and-a-con

* sceme
      OS <- Shell <- ввод 
      OS <- API <- GUI <- APP <- ввод
* First cmds
ls
ls -a # dotfiles
ls -l
ls -la
cd dir
cd ..
cd ~
cd
touch newfile
cp file newfile
cp -r dir newdir
mv file rfile
rm file
mkdir dirname
rmdir dirname
rm -r dir
echo
curl wttr.in Rybinsk

date
cat
less
file

locate
ls -S
ls -t
man
head
tail
ps
top
kill PID
pkill
xkill
df
free
