#!/bin/bash
cat dotfiles/bashadd >> ~/.bashrc 
mkdir -p ~/.config/i3
mkdir -p ~/.vim/autoload
cp dotfiles/Linux/configs/.vim/autoload/plug.vim ~/.vim/autoload/
cp dotfiles/.vimrc ~/
cp dotfiles/.tmux.conf ~/
cp dotfiles/.xprofile ~/
cp dotfiles/.xbindkeysrc ~/
cp dotfiles/Linux/configs/i3/config ~/.config/i3/
loadkeys us-caps
#xinit
