#!/bin/bash
# vim: filetype=sh
HOST=127.0.0.1
PORT=5432
USER=lod
PGPASSWORD=wa8va128
DB=lod_db
TABLE=$1
pg_cmd="psql -h $HOST -p $PORT -U $USER $DB "
shownext=0
end="-n"
for line in `echo "\d $TABLE" | $pg_cmd | sed -e '1,/Foreign-key/d' | sed -e '/Referenced/,$d'`; do
    if [ $shownext = 1 ]; then
        line=$(echo $line | sed -e 's/(id)//')
        line=$(echo $line | tr -d '()')
        echo $end $line ':'
        shownext=0
    fi
    case $line in
        KEY) 
            shownext=1
            end="-n" 
            ;;
        REFERENCES)
            shownext=1
            end=""  
            ;;
    esac
    
done

#read
