#!/bin/bash
# vim: filetype=sh
echo 'digraph { '
echo 'rankdir="LR";'
echo 'splines=polyline;'
tables=./get_tables
tables="cat ./tables"

for table in $($tables); do
    echo "$table[shape=box, fillcolor=\"darkolivegreen2\", style=\"filled\"]"
    ./gen_graph $table
done

echo '}'
