Pacman catfish
Реализация на javascript
Отображение в браузере
* Этап 1
Есть игровое поле. Одинакового вида. Заполненно съедобными точками.
Выводить количество съеденных точек, игровое поле, pacmana.
Управление - стрелки и WASD для направления движения.
Механика:
Pacman изначально стоит на месте.
При нажатии кнопки движения в сторону ближайшей клетки свободной от стены - начинать двигаться в этом направлении.
При достжении стены в данном направлении - остановиться.
При движении через точку - съедать её.
Через определенных промежуток времени происходит обновление всего поля,
обработка нажатых кнопок, движение pacmana, съедание точек.

Анимация самого pacmana.
Анимация движения по клеткам.

При съедании всех точек, поле восстанавливается, pacman ставится в начало, начинается новая игра.

** 0.
- Нарисовать эскиз.
** 1.
- Сделать вывод игрового поля - стен.
      - Добавить вывод точек.
      - Добавить вывод pacmana.
      - Добавить вывод количества съеденныих и оставшихся точек.
** 2.
- Сделать главный цикл игры.
      - движение pacmana.
      - обработка нажатий.
      - обработка столкновений со стенами и точками.

* 0 реализация
сделать html со стилями того как оно должно выглядеть
* 1 реализация
сделать базовую страницу, подключить скрипт.
Создать (и вызвать) функцию формирования лабиринта.
(таблица с границами?)
сделть формирования лабиринта основываясь на массиве описывающем стены
