#!/bin/bash
# vi: filetype=sh
echo "Tomcat home is $1"
echo 'java x max heap script started' 
#setenv_content=$(cat ${1}bin/setenv.sh)
java_run_line=$(jps -lmv | grep Xmx)
java_run_lines=$(echo $java_run_line | tr - '\n')
java_run_mem=$(echo -e "$java_run_lines" | sed -n '/^X/p' | cut -d x -f 2)
echo "$java_run_lines" 
echo "$java_run_line" 
echo "$java_run_mem" 

#for line in $java_run_lines; do echo $line; done
#echo -e $java_run_mem
suffix=$(echo -e "$java_run_mem" | tail -c 3 | head -c 1 | tr [:lower:] [:upper:])
echo "$suffix" 
java_mem_num=$(echo -e "$java_run_mem" | tr -d [:alpha:] )
echo "$java_mem_num" 
#echo $java_mem_num
#echo "${suffix}"
if [ "$suffix" = 'M' ]; then
    echo "$(expr 1024 \* 1024 \* $java_mem_num)"
elif [ "$suffix" = 'G' ]; then
    echo "$(expr 1024 \* 1024 \* 1024 \* $java_mem_num)"
else
    echo 123
fi

