#!/bin/bash
while read -ra ITEM; do
  for i in "${ITEM[@]}"; do
    git checkout $i
    echo ======================== $i
    OLD_COMMIT=$(git show --format="%H" HEAD | head -n 1)
    git pull
    NEW_COMMIT=$(git show --format="%H" HEAD | head -n 1)
    #echo $OLD_COMMIT $NEW_COMMIT
    if [ "$OLD_COMMIT" = "$NEW_COMMIT" ]; then
        echo "SAME"
        continue;
    fi
    #
	#echo $GIT_BRANCH $GIT_PREVIOUS_COMMIT $GIT_COMMIT
    echo $(git diff -U0 $GIT_PREVIOUS_COMMIT $GIT_COMMIT -- *.py **/*.py )
    echo $(git diff -U0 $GIT_PREVIOUS_COMMIT $GIT_COMMIT -- *.py **/*.py | pycodestyle --diff)
    EMAIL=$(git show --format="%aE" $GIT_COMMIT | head -n 1)
    #echo $EMAIL
    if ! git diff -U0 $GIT_PREVIOUS_COMMIT $GIT_COMMIT -- *.py **/*.py | pycodestyle --diff; then
          ERRORS=1
          echo ERROR
          #BODY=$(git diff -U0 $GIT_PREVIOUS_COMMIT $GIT_COMMIT -- *.py **/*.py | pycodestyle --diff)
          $(git diff -U0 $GIT_PREVIOUS_COMMIT $GIT_COMMIT -- *.py **/*.py | pycodestyle --diff) | mail -s styleErrors $EMAIL
    fi

	echo ========================___
  done
done <<< $(git branch -r | grep -v "HEAD ->" | xargs -L 1 | cut -d'/' -f2)

exit $ERRORS

