#!/bin/bash
source net_names
ip link set $ETH up
dhcpcd 
pon atel
for i in 1 2 3 4 5; do
if ip link show ppp0 >/dev/null 2>/dev/null ; then
    break
fi
echo "$i) Wait sec for ppp0..."
sleep 1
done
sleep 1
dhcpcd 
sleep 1
ip route add default dev ppp0
