https://purecodecpp.com/
https://habr.com/ru/post/497158/
https://isocpp.org/faq
Да всё интересное зачастую на С++ вот и надо доучить!
Учить читать интересные темы в книгах сразу и разбираться и пробовать.
составить список тем 
* TODO
>https://trac.ietf.org/trac/netconf/wiki

>https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/
* debug
>http://dbp-consulting.com/tutorials/debugging/basicAsmDebuggingGDB.html
>http://rus-linux.net/nlib.php?name=/MyLDP/algol/gdb/otladka-s-gdb.html#SEC4
>https://habrahabr.ru/post/328180/

* books
- read :: >http://pv.bstu.ru/oop/c++/cpprules.pdf

* stl
>https://i.stack.imgur.com/d5CDK.png
>http://alenacpp.blogspot.ru/2006/12/vector-vs-deque.html
>http://www.cplusplus.com/reference/iolibrary/
* boost
Boost.Spirit для domain lang
>https://habrahabr.ru/post/192284/

* sites
>http://cpp.sh/36tg
>http://cppstudio.com/cat/285/289/
>http://cpp.com.ru/
>https://ru.wikipedia.org/wiki/New_(C%2B%2B)#Placement_new
>http://alexkutsan.blogspot.ru/2012/10/stdvalarray-stdslice.html
>http://ru.cppreference.com/w/cpp/utility/functional/function
>http://sysdev.me
>http://kaisar-haque.blogspot.ru/2008/07/c-accessing-virtual-table.html
>https://lucabolognese.wordpress.com/2013/01/04/functional-programming-in-c/
>https://ru.wikipedia.org/wiki/Functional_(C%2B%2B)
>http://alenacpp.blogspot.ru/2006/09/blog-post_19.html
>http://cpp.com.ru/
>https://code-live.ru/post/cpp-variables-and-datatypes/

* enum
>http://www.cpplessons.in.ua/enum-class-%D1%81%D1%82%D1%80%D0%BE%D0%B3%D0%BE-%D1%82%D0%B8%D0%BF%D0%B8%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD/
>http://www.quizful.net/post/enum-types-c

* types
>https://habrahabr.ru/post/106294/
>http://alenacpp.blogspot.ru/2005/08/c.html
>http://alenacpp.blogspot.ru/2008/01/const.html
>https://www3.ntu.edu.sg/home/ehchua/programming/cpp/cp4_PointerReference.html
>https://habrahabr.ru/post/301332/
>https://habrahabr.ru/post/142662/
>https://en.wikipedia.org/wiki/Return_value_optimization
>https://web.archive.org/web/20130912001311/http://cpp-next.com:80/archive/2009/08/want-speed-pass-by-value/
>https://stackoverflow.com/questions/17473753/c11-return-value-optimization-or-move/17473869#17473869

* oop
>https://habrahabr.ru/post/64280/

* c++11
>https://habrahabr.ru/post/182920/

* tools
>http://www.trumphurst.com/cpplibs6.html

* Libs
astyle
valgrind
gcov
ccache
Bison Yacc
** Qt
>https://habrahabr.ru/post/50812/
>http://doc.qt.io/qt-5/qtnetwork-programming.html
>https://wiki.qt.io/New_Signal_Slot_Syntax/ru
>https://samdutton.wordpress.com/2008/10/03/debugging-signals-and-slots-in-qt/
>https://ru.wikibooks.org/wiki/Qt/%D0%A7%D0%90%D0%92%D0%9E

* build
>https://habrahabr.ru/post/330902/

* C++
  отрефакторить игру на с
  переписать скрипты и проги некоторые
  сделать базовые задачи
  выучить все типы
  изучить особенности и хитрости(хабри хитрости с++)
  и конструкции и объявления
  разобраться с configure, automake etc
  gdb
  profiling
  enable warnings
  objdump (-d -x)
  unittest
  linux syscalls

  #pragma once  для однкратного включения хидера.
  объявление \ определение
    определение -> выделение памяти
    объявление переменной - extern, функции - заголовок.
    объявить можно несколько раз но не определить.
  man -f, man sys call
  sudo !! # !! - last command
  c++filt -n
  c++ shell

* job 1
>>wrap C++ lib (https://github.com/fnc12/sqlite_orm)
>>as n-api module for node.js
>>https://nodejs.org/dist/latest-v10.x/docs/api/n-api.html
