Алгоритмы проги которые будут рисовать, генерить изображения..
support.mosreg.ru/static/humans.txt
https://processing.org/
http://progstone.narod.ru/reciprocality/r0/day1.html
https://github.com/jwasham/coding-interview-university#binary-search
https://github.com/danistefanovic/build-your-own-x

* Framework from patterns 41
Каркас это набор взаимодействующих классов, составляющих повторно
используемый дизайн для конкретного класса программ. Он диктует определенную
архитектуру приложения, определяет общую структуру, её разделение на классы и
объекты, основные функции тех и других, методы взаимодействия объектов и
классов и потоки управления. В каркасе аккумулированы проектные решения,
общие для данной предметной области. 


* carnegy
В самом деле, существует один способ в подлунном мире оказать влияние на другого человека: это говорить с ним о том, что является предметом его желаний, и показать ему, как можно этого достичь.
...подумайте: каким образом можно заставить его захотеть сделать это?

* ratio
Если ты не стремишься к совершенству, ты остановишься еще до того, как сделаешь свои первые шаги
* Pat
декорация как наследование, расширяем базовый класс, сохраняем ссылку на
экземпляг декорируемого и подменяя интрефейс используем базовые, делегируем
основную часть интерфейса.

Мне нужен приспособленец для симуляции многих. значит будут
конкретно-абстрактные существа в одном экземпляре и контексты(положение, др.  свойства)
      нужна фабрика таких объектов. и для полушения.
      но только если внешних состояний меньше.

* unix
Органичение побуждает не только к экономии, но и к опрелелённому изяществу дизайна.
