Чтение книг прибавляет навыки но это реальные книги, статьи - надо прочитать и понять и ответить на тест. причё по теме, холодное оружие - тест по этому.

https://habr.com/ru/post/536140/
clicker, idle, incremental, upgrade. + rpg + story + music
Сделать игру кликер. (clicker game) прогресс там и всякое.
https://habr.com/post/354826/#habracut
https://en.wikipedia.org/wiki/List_of_open-source_video_games
https://www.shadertoy.com/view/ldfyzl
genetic algo for actors learning, evolving algo. 
(resource - food, breeding, mutate)
behavior from mini lang - go udlr, if, 

>https://vimeo.com/135596203
модели с обраными связями в + и -
настроение акторов, модель психологии
>https://www.youtube.com/watch?v=uc5rfTkLzlY
>!!!!!! http://ncase.me/
>https://github.com/rastapasta/mapscii
* behavior strateg's
simulate as other
always good
always bad

errors in behave
* rogue
>http://www.locklessinc.com/articles/512byte_roguelike/
>http://roguelikeeducation.org/1.html
>http://www.roguebasin.com/index.php?title=Data_structures_for_the_map
>http://www.roguebasin.com/index.php?title=How_to_Write_a_Roguelike_in_15_Steps
>http://www.roguebasin.com/index.php?title=Complete_Roguelike_Tutorial,_using_python%2Blibtcod
>http://www.roguebasin.com/index.php?title=Code_design_basics
>https://gamedevelopment.tutsplus.com/tutorials/how-to-use-bsp-trees-to-generate-game-maps--gamedev-12268
>https://vc.ru/p/gamedev-challenges-2

* sdl
>http://lazyfoo.net/SDL_tutorials/index.php

* 2d
>https://habrahabr.ru/post/313776/
* 3d
** ray
>https://habrahabr.ru/post/175285/

* sound
>https://gamedev.stackexchange.com/questions/22525/how-should-a-one-man-team-do-game-audio
>http://www.keygenmusic.net/?lang=ru

* res
>https://opengameart.org/content/mage-city-arcanos
>http://spritedatabase.net/file/19901

* pixelart
>http://finalbossblues.com/using-and-choosing-colors/
>https://gamedevelopment.tutsplus.com/tutorials/how-to-use-bsp-trees-to-generate-game-maps--gamedev-12268
>http://gas13.ru/v3/tutorials/

* game desing
>https://habrahabr.ru/post/330810/
>https://habrahabr.ru/post/316126/

* 2.2 игры (TZ_platformer, TZ_survival, TZ_games) roguelike
        в игре должен быть элемент Большого шага мира, после которого происходит моного событий и хочется поиграть ещё и ещё.
        или даже несколько видов таких шагов и прогресса. типа сначала дни(часы), потом неделя, месяц...
        и бесконечное развитие но имеющее смысл(новые вызовы, новое...) и не ясно сначала что можно развиться ещё и ещё и
         разные виды развития и переразвития.
        Инвенталь наподобие элоны
        редактор объектов, формат Yaml (ценность объекта... тип)
    Progress game. semiAuto, text. выбрал - идти найти монстра, бить... прогресс.. замах.. удар, иду, поднимаю предмет.
        клики ускоряют чуток. кач ускоряет действия некоторые?
        или как работа - ежедневно ходить в данж, разноуровневый. покупать шмот самому игроку...
        Описывать что видит и происходит. Ограниченный инвентарь - список 10,
        при выборе список возможных действий. Для квеста что как?

* учиться рисовать пиксель арт.
* Изучать sunvox или другое
* roguelike
      Сделать сначала отображение символов из png атласом. Используя SDL
      Можно сделать красивую консоль.
            мягко мигающие символы. c матрицей фоном.
            со схемами и бегущими сигналами
            как я вижу консоль, и магию символов и вычислений.
* rogue jrpg
      terminal graphic + jrpg
      random encounters
      battle system (HOW display) side view, menu

.___. .___. .___.
|   | |   | |. .| 
| . | | : | | . | 
\___/ \___/ \___/ 
.___. .___. .___.
| : | | : | |...| 
| : | |...| |...| 
\___/ \___/ \___/ 
