https://github.com/trekhleb/javascript-algorithms
https://www.html5rocks.com/en/tutorials/canvas/imagefilters/
https://webformyself.com/node-js-buffer-bufery/
https://nodejs.org/api/process.html#process_process_platform
https://moment.github.io/luxon/
https://www.d3indepth.com/geographic/
https://sohabr.net/habr/post/335510/
https://habr.com/ru/post/148098/
https://habr.com/ru/post/319270/
https://reactjs.org/docs/getting-started.html
https://xtermjs.org/
https://habrahabr.ru/post/351656/#habracut
http://meritt.github.io/rubles/
https://github.com/agershun/alasql
https://github.com/pouchdb/pouchdb
https://dhtmlx.com/
https://habrahabr.ru/post/38208/
https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills
>https://habrahabr.ru/company/ruvds/blog/338150/
* сеть\граф блокнот записи на жс ангуляр2 с клавы? два режима - работа с графом
 с чего начать? настроить базовое рабочее окружение. разработать структуру
 данных. Спроектировать интерфейс, разбить на модули. выделить зоны ответственности.
 можно ли сделать как раз для такого рода записей и логических рассуждений и
 для ведения дел удобное приложение. удобство должно быть заключено в быстром
 переходе от одной записи к другой, закладки. 
 Что делать с проблемой управления с клавиатуры - мешает вим мод в фф.
   варианты: отключить совсем - но тогда браузить остальное неудобно.
     отключить только для определенного урл, как? - ignorekeys add site.com
 решено. Значит как перехватывать все нажатия? на body keydown?

>http://metanit.com/
>http://www.w3schools.com
>https://learn.javascript.ru
>http://javascript.ru/manual
>https://learn.javascript.ru/external-script
>https://learn.javascript.ru/types-conversion
>http://metanit.com/web/angular/
>https://habrahabr.ru/post/309300/
>http://topolyan.com/w3c/w3c-dom4-ru.html
>https://getfirebug.com/wiki/index.php/Command_Line_API
>https://www.liveedu.tv/learn/backbone-js/
>https://karma-runner.github.io/1.0/index.html
>https://habrahabr.ru/company/rambler-co/blog/278503/
>http://webdriver.io/

* jq
>http://youmightnotneedjquery.com/
>http://www.w3schools.com/jquery/traversing_find.asp
>https://api.jquery.com/find/
>http://tutorialzine.com/2014/06/10-tips-for-writing-javascript-without-jquery/

* tools
>https://jsfiddle.net/
touse: linter, mochajs.org gulp/grunt eslinter babel
>http://plnkr.co/
>http://sinonjs.org/
>http://chaijs.com/
* libs
>http://momentjs.com/
>https://babeljs.io/
>http://eslint.org/
>http://webdriver.io/
>https://facebook.github.io/react/
>https://maxfarseer.gitbooks.io/react-course-ru/content/

* exer
>https://the-winter.github.io/codingjs/?utm_content=buffer83040&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer
