* zenity bug#786395
* 1
Hi.
I am newcomer. I read Newcomers Guide. I choose zenity project for start. Cloned git repo.
I explored in master branch this bug:
https://bugzilla.gnome.org/show_bug.cgi?id=786395
And find some solution and then post to bugzilla and attached a patch.
I was not used JHBuild (maybe it is enough for such bug).

Can you view and help, please?

Also I found a bug: list in forms dialog is not viewable without other widgets which correctly expands to the full dialog window width.

Test cases:
# not full width
zenity --forms --add-list="foo"
zenity --forms --add-list="foo" --list-values="1|2"
# full width
zenity --forms --add-list="foo" --add-entry="blank"

Best regards.


Hi.
I explored this bug.
When a form has two (and more) lists and not enougth list values, the second (and all following lists) list has not column_types, therefore it crashes.
I suggest to set column_types to G_TYPE_STRING by default if values not provided (see patch).

Test case:
zenity --forms --add-list="foo" --add-list="bar" --add-list="car" --list-values="1|2|3" --add-entry="blank"

>>https://developer.gnome.org/gtk-tutorial/stable/c1226.html
find how autosize (scroll) container

diff --git a/src/forms.c b/src/forms.c
index 49d2bbb..a1d28ed 100644
--- a/src/forms.c
+++ b/src/forms.c
@@ -174,7 +174,7 @@ zenity_forms_create_and_fill_list (
 	// (scrolled_window),
 	//                                       GTK_WIDGET (tree_view));
 	gtk_container_add (GTK_CONTAINER (scrolled_window), GTK_WIDGET (tree_view));
-	gtk_widget_set_size_request (GTK_WIDGET (scrolled_window), -1, 100);
+	gtk_widget_set_size_request (GTK_WIDGET (scrolled_window), 100, 100);
 	gtk_tree_view_set_headers_visible (
 		GTK_TREE_VIEW (tree_view), forms_data->show_header);


MSG: 
src/forms.c: Fix segfault on multiple lists without values

If was not provided enought list-values for add-list options then column_types is NULL.
Therefore need set it to default value.
If count of columns values less than count of list values then set column nubmer to zero.

* 2
I get it.

Column values and list values must count separately.
Column values must correspond to list values therefore column number must
correspond list number.

g_slist_nth_data (forms_data->column_values, list_number);

Using there list_number is not valid - it possible that count of columns less
than count of lists.  In such case, we may use first column for all remaining columns.
