#!/bin/bash

### Services run
source ~/dotfiles/linux/.env
pidof sxhkd >/dev/null || (nohup sxhkd >/dev/null 2>&1 & disown)
dunst &
picom &
numlockx on
#NO_TMUX=1 guake &
guake &
[ ! -s ~/.config/mpd/pid ] && mpd
# thunar --daemon &
greenclip daemon &

### Globas settings
xrdb "/home/$(whoami)/.Xresources"
hsetroot -solid "#000"
#setxkbmap -layout us,ru -option "grp:alt_shift_toggle,grp_led:scroll" &
setxkbmap -option caps:escape
ibus-daemon -drx

### Desktops by monitor config
bspc config remove_unplugged_monitors true

if [ -z $MONITOR_1 ]; then
    bspc monitor -d 1 2 3 4 5 6 7 8 
elif [ "$MONITOR_COUNT" = '2' ]; then
    bspc monitor $MONITOR_1 -d 1 2 3 4
    bspc monitor $MONITOR_2 -d 5 6 7 8 
else
    bspc monitor $MONITOR_1 -d 1 2 3 4 5 6 7 8 
fi

### Window config
bspc config border_width         0
bspc config window_gap           0
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

### Apps rules
bspc rule -a Google-chrome desktop='^2'
bspc rule -a St state=fullscreen
bspc rule -a mpv state=fullscreen
bspc rule -a Anki desktop='^3'
bspc rule -a Code desktop='^1' state=fullscreen
bspc rule -a Slack desktop='^3' state=fullscreen 
bspc rule -a TelegramDesktop desktop='^5'
bspc rule -a Guake state=floating
bspc rule -a PureRef state=floating
bspc rule -a Peek state=floating
bspc rule -a Zathura state=tiled
bspc rule -a clipstudiopaint.exe state=floating
#bspc rule -a jetbrains-webstorm desktop='^1'
bspc rule -a kitty:dropdown-term state=floating sticky=on hidden=on center=on follow=on
bspc rule -a kitty state=fullscreen
# bspc rule -a kitty:btop desktop='^3'
bspc rule -a GuakeKitty state=floating sticky=true rectangle=900x400+250+0


### Auto run apps
nm-applet &
dropboxd &
$HOME/.config/polybar/launch.sh
#run-if-not kitty
pidof chrome >/dev/null || google-chrome &
kitty --title btop btop &
# pidof anki >/dev/null || anki &
# pidof Telegram >/dev/null || Telegram &

monitors-setup
# Display to enter DPMS (Display Power Management Signaling) states after 30 minutes of inactivity
xset dpms 1800 1800 1800 # Standby, Suspend, Off
