#!/bin/bash

### Services
# source ~/dotfiles/linux/.bashrc
source ~/dotfiles/linux/.env
pidof sxhkd >/dev/null || (nohup sxhkd >/dev/null 2>&1 & disown)
setxkbmap -option caps:escape
dunst &
picom &
NO_TMUX=1 guake &
[ ! -s ~/.config/mpd/pid ] && mpd
# thunar --daemon &

xrdb "/home/$(whoami)/.Xresources"
hsetroot -solid "#202020"
setxkbmap -layout us,ru -option "grp:alt_shift_toggle,grp_led:scroll" &

### Config
if [ -z $MONITOR_1 ]; then
    bspc monitor -d 1 2 3 4 5
elif [ "$MONITOR_COUNT" = '2' ]; then
    bspc monitor $MONITOR_1 -d 1 2 3 4 5
    bspc monitor $MONITOR_2 -d 6 7 8 9 10
else
    bspc monitor $MONITOR_1 -d 1 2 3 4 5
fi

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Google-chrome desktop='^2'
bspc rule -a kitty desktop='^1' state=fullscreen
# bspc rule -a kitty state=floating rectangle=800x600+100+100
bspc rule -a St state=fullscreen
bspc rule -a mpv state=fullscreen
# bspc rule -a Org.gnome.Nautilus desktop='^10' state=fullscreen monitor=DP-3
bspc rule -a thunar desktop='^2'
bspc rule -a Code desktop='^1' state=fullscreen
bspc rule -a Slack desktop='^3' state=fullscreen 
bspc rule -a TelegramDesktop desktop='^8'
bspc rule -a obsidian desktop='^9'
bspc rule -a obs desktop='^10'
bspc rule -a Audacious desktop='^9'
bspc rule -a Transmission-gtk desktop='^10'
bspc rule -a Guake state=floating
bspc rule -a Peek state=floating

### Apps
nm-applet &
dropbox start &
$HOME/.config/polybar/launch.sh
#run-if-not kitty
#pidof obsidian >/dev/null || obsidian
pidof kitty >/dev/null || kitty &
pidof chrome >/dev/null || google-chrome &
pidof slack >/dev/null || slack &
pidof Telegram >/dev/null || Telegram &

bspc rule -r kitty
bspc rule -a kitty state=fullscreen
