
-- {
--   'iamcco/markdown-preview.nvim',
--   ft = 'markdown', -- Only load when editing markdown files
--   build = 'cd app && npm install',
-- },
-- { TODO find alternative wihotu set termguicolors in lua
--   'norcalli/nvim-colorizer.lua',
--   -- event = 'BufReadPost',
--   config = function()
--     require('colorizer').setup()
--   end,
-- },
---- transparent background
-- vim.api.nvim_set_hl(0, 'Normal', { bg = 'none' })
-- vim.api.nvim_set_hl(0, 'NormalFloat', { bg = 'none' })
-- vim.api.nvim_set_hl(0, 'FloatBorder', { bg = 'none' })
-- vim.api.nvim_set_hl(0, 'Pmenu', { bg = 'none' })
