#!/bin/bash
# vim: filetype=sh
BRANCH=$1 # = branch
PORT="8$(echo $BRANCH | tr -d '[:alpha:]')"
NAME=$2

if [ -z $NAME ];then 
    NAME='support'
fi

DIR="${BRANCH}_$NAME"

case $NAME in
    support)
    echo deploy Support
    git clone http://TikhomirovSVl@bitbucket.mosreg.ru/scm/sup/self-support.git $DIR
        ;;
    qa)
    echo deploy qa site
    git clone http://TikhomirovSVl@bitbucket.mosreg.ru/scm/sup/qasite.git $DIR
        ;;
    feed)
    echo deploy feedback
    git clone http://TikhomirovSVl@bitbucket.mosreg.ru/scm/sup/mosreg-survey.git $DIR
    ;;
esac

(cd $DIR; make init)
(cd $DIR; git config --local user.name "anokata")
(cd $DIR; git stash)
(cd $DIR; git checkout $BRANCH)
(cd $DIR; make prun PORT=$PORT)

