#!/bin/bash
# vim: filetype=sh
# watch N sec and check and notify if down
ico=~/work/master_feed/media/img/favicon.png
check() {
    URL=$1
    WORD=$2
    if  curl -k -A "-- Monitoring" -s $URL | grep $WORD > /dev/null ; then
        echo -e "up \t $URL"
    else
        echo down
        notify-send -h int:x:500 -h int:y:500 -i $ico -u critical Test "$URL Portal DOWN"
    fi
}

#check http://portal.support.mosreg.ru/login password
#check http://feedback.mosreg.ru/ mosreg 
check https://support.mosreg.ru/portal/login password
check https://support.mosreg.ru/feed/ mosreg 
check https://support.mosreg.ru/ mosreg
check http://ext.support.mosreg.ru/portal/ mosreg

