#!/bin/bash
# vim: filetype=sh
# watch N sec and check and notify if down
check() {
    URL=$1
    WORD=$2
    if  curl -s $URL | grep $WORD > /dev/null ; then
        echo up
    else
        echo down
        notify-send -h int:x:500 -h int:y:500 -i hexchat -u critical Test "Portal DOWN"
    fi
}

check http://portal.support.mosreg.ru/login password
check http://feedback.mosreg.ru/ mosreg 
check http://support.mosreg.ru/ mosreg
