#!/bin/bash

# get py changed files list
for f in $(git diff --cached --name-only | grep .py); do
    git diff --cached $f | pycodestyle --diff 
    #pycodestyle $f
done
# get diff and pep it

exit 1
