#!/bin/bash
ERRORS=0

for file in $(git diff --cached --name-only); do
    if ! git diff -U2 --cached $f | pycodestyle --diff; then
        ERRORS=1
    fi
done 

if [[ $ERRORS = 1 ]]; then
    echo Style errors, reject!
fi
exit $ERRORS
