install:
	echo 'source ~/dotfiles/linux/.bashrc' >> ~/.bashrc
	echo 'source ~/dotfiles/linux/.env' >> ~/.profile
config:
	./install.dirs.sh
	./install.configs.sh -p
	./install.apps.sh
	./install.ext.sh
	./install.vim.sh -p
