- hosts: all
  tasks:
      - name: Install packages
        yum: name={{ item }} state=present
        become: true
        with_items:
            - sudo 
            - tmux 
            - vim
            - ctags
            - git
            - tree 
