#!/bin/bash
# vim: filetype=sh
echo run with sudo
name=$1
if [ -z $name ]; then exit 1; fi

lxc-create -n $name -t centos
lxc-start -n $name
lxc-ls -f $name | tail -n1
IP=$(sudo lxc-ls -f dc1 | tail -n1 | cut -d- -f 2 | tr -d [:space:])
echo $IP

lxc-attach -n $name -- sed -i -e "\$aPermitRootLogin yes" /etc/ssh/sshd_config
lxc-attach -n $name -- adduser psi
lxc-attach -n $name -- usermod -a -G wheel psi
lxc-attach -n $name -- ssh-keygen -q -f /root/.ssh/id_rsa -N ''
#lxc-attach -n $name -- sed -i 's|[#]*PasswordAuthentication yes|PasswordAuthentication no|g' /etc/ssh/sshd_config
#lxc-attach -n $name -- sed -i 's|UsePAM yes|UsePAM no|g' /etc/ssh/sshd_config
lxc-attach -n $name -- service sshd restart

lxc-attach -n $name -- passwd

#ssh root@$IP
#http://www.panticz.de/ssh_pre-shared-key_authentication

# deploy

