#!/bin/bash
# vim: filetype=sh
DATE=$(date +%Y.%m.%d-%H.%M)
PGHOST=127.0.0.1
PGPORT=5432
PGUSER=$2
DB=$1
USER=$(whoami)
PREFIX=$HOME/backups
mkdir -p $PREFIX || true
mkdir -p $PREFIX/last || true
DUMPNAME="$PREFIX/${DB}_$DATE.sql.gz"
echo "DUMPING to  $DUMPNAME"
#mkdir bkp_$DATE 
#PGPASSFILE=./pgpass
PGPASSWORD=
echo DUMPING
pg_dump -h $PGHOST -p $PGPORT -U $PGUSER -Ovx $DB | gzip --best > $DUMPNAME
chown $USER:$USER $DUMPNAME
chmod a+r $DUMPNAME
chmod a+r $PREFIX/last
echo Copy to last
rm $PREFIX/last/* || true
#cp $DUMPNAME $PREFIX/last/${DB}.last.sql.gz
cp $DUMPNAME $PREFIX/last/
