#!/bin/bash
# vi: filetype=sh
PREFIX=$HOME/backups
mkdir $PREFIX || true

name1=support

qas=http://bitbucket.mosreg.ru/scm/sup/qasite.git
sup=http://bitbucket.mosreg.ru/scm/sup/self-support.git
fee=http://bitbucket.mosreg.ru/scm/sup/mosreg-survey.git
sup=ssh://git@bitbucket.mosreg.ru:7999/sup/self-support.git
qas=ssh://git@bitbucket.mosreg.ru:7999/sup/qasite.git
fee=ssh://git@bitbucket.mosreg.ru:7999/sup/mosreg-survey.git

git clone $qas /tmp/qas
git clone $sup /tmp/support
git clone $fee /tmp/feedback

(cd /tmp; tar -czf qa.tar.gz /tmp/qas)
(cd /tmp; tar -czf sup.tar.gz /tmp/support)
(cd /tmp; tar -czf fee.tar.gz /tmp/feedback)
cp -f /tmp/qa.tar.gz $PREFIX
cp -f /tmp/sup.tar.gz $PREFIX
cp -f /tmp/fee.tar.gz $PREFIX
rm -rf /tmp/qas
rm -rf /tmp/support
rm -rf /tmp/feedback
#ls -lah $PREFIX/*.gz
